### ISSUE TITLE
Recommendations Page does not change after initial onboarding

### ISSUE THREAD

**Issue by azatecas** [Lambda-School-Labs/Groa-be#28]
Currently, Recommendations api does not change movie recommendations displayed on the front end. you can rate movies but the list doesn't change

**Comment by moviedatascience** [comment]
Thankfully now we located the issue of recommendations not being written to the db. 

Additionally recommendations will be loaded from the Json return from the API from now on, so once the front end is reconfigured we can take the data directly from the JSON response and populate the recommendations page.
