### ISSUE TITLE
Sign-up/Login is broken

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#34]
## Expected Behavior
User should be able to sign into Groa or create an account.

## Current Behavior
Selecting login after entering a username and password does nothing.

## Possible Solution
I'm pretty sure this is due to Login and Signup pulling from the DB that Doina closed down on Friday afternoon. 

If we can get the routes corrected so that the login information is pulled from the new DB this issue should be resolved.

## Steps to Reproduce
1. Navigate to https://www.groa.us/login
2. Enter Username and Password
3. Select Login
4. Observe no action 

## Context (Environment)

This occurs on both register and login.

**Comment by Steven-matos** [comment]
fixed the environment variable in Elastic Beanstalk for the database.
