### ISSUE TITLE
Watchlist page is mislabeled as "Wishlist"

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#36]
## Expected Behavior
"Wishlist" page in the navigation bar should be renamed to "Watchlist" and load the watchlist page.

## Current Behavior
Watchlist is named "Wishlist" in the navbar and routes to a non-existant "Wishlist" page.

## Possible Solution
Changing the name in the navigation bar as well as the route to "watchlist"

## Steps to Reproduce
1. Navigate to https://www.groa.us
2. Expand the lefthand hamburger menu
3. Select "Wishlist"
4. Observe no page load

## Context (Environment)

Going to https://www.groa.us/userID/watchlist does still properly load and function.

**Comment by jvillalp** [comment]
Wishlist edited to 'watchlist', loads to watchlist page, but no data is displaying yet.
