### ISSUE TITLE
Recommendations Page does not return Recommendations

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#37]
## Expected Behavior
User should receive recommendations when navigating to the Recommendations page.

## Current Behavior
A white screen is returned instead of the Recommendations page.

## Possible Solution
Parsing the returned Json from the DS API instead of querying the DB should result in the BE being able to format and serve Recommendations

## Steps to Reproduce
1. Navigate to https://www.groa.us/userid/recommendations
2. Observe a white screen.

## Context (Environment)

This will require both a rework of how the site calls the API and how the data is served on the front end.

**Comment by Steven-matos** [comment]
the fix is implemented on front-end [PR #79](https://github.com/Lambda-School-Labs/Groa-fe/pull/79)
