### ISSUE TITLE
Watchlist Lists Movies Multiple Times

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#41]
## Expected Behavior
Watchlist should be populated with only one instance of each movie.

## Current Behavior
Many instances of the same movie are populating on the watchlist page.

## Possible Solution
Putting a constraint on the watchlist page to only load a single instance of each (Movie)(Year) combination should be a band-aid fix. 

## Steps to Reproduce
1. Navigate to https://www.groa.us/userid/watchlist
2. Scroll down.
3. Observe several instances of the same movie appearing

## Context (Environment)

Some additional exploration would be a good idea to find out exactly what is causing this so we can potentially fix similar problems elsewhere.

**Comment by moviedatascience** [comment]
Attached are images of movies appearing in two different places in the Watchlist screen.

![thx1](https://user-images.githubusercontent.com/7471385/80513101-8f204d00-894c-11ea-95f2-7c96f54b8f8d.PNG)
![thx2](https://user-images.githubusercontent.com/7471385/80513103-90517a00-894c-11ea-8852-3c8db503fc1d.PNG)

**Comment by Steven-matos** [comment]
At this time there is only one instance of the movie in the watchlist
