### ISSUE TITLE
Links to Service Providers should populate a new window

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#71]
## Expected Behavior
When the user clicks on a service provider link they should be taken to a new window. 

## Current Behavior
The link takes them to a new screen within the same window.

## Possible Solution
I think there's a variable to set the behavior for link click. 

## Context (Environment)

This way someone can go watch the movie and not lose their place when they want to rate it afterwards.

**Comment by msinnema33** [comment]
Fixed with FE PR #148.
