### ISSUE TITLE
Not Interested Button does not add movie to user_willnotwatchlist

### ISSUE THREAD

**Issue by moviedatascience** [Lambda-School-Labs/Groa-be#72]
## Expected Behavior
When a user selects "Not interested" the movie is added to the user_willnotwatchlist 

## Current Behavior
When a user selects "Not interested" the text changes to "Removed from results" but the title is not added to the user_willnotwatchlist table.

## Possible Solution
I assume the information is not being sent to the DS endpoint /notwatchlist . 

The following information needs to be sent to that endpoint:

`{
  "movie_id": "string",
  "user_id": "string"
}`

## Context (Environment)

I looked in the DB and my user has movies in there but none after the 20th. 

If I had none I would be inclined to think it was something wrong with the DS API but since some are populating but they stopped after the 20th I think something must have changed in the web code call to the API.

**Comment by moviedatascience** [comment]
When I check the console I'm getting:

`ADDING_NOTWATCHLIST_FAIL `

**Comment by moviedatascience** [comment]
Oh I see what's wrong, the code has the user_id in the URL request to the endpoint instead of a payload. That must have been a change made on the DS side without letting you all know.

**Comment by Steven-matos** [comment]
Issue was resolved due to an env variable update.
